package auth

import (
	"jellyfin-hls-server/internal/config"

	"github.com/gin-gonic/gin"
)

func CreateAuthenticateUserResponse(
	userId string,
	accessToken string,
	cfg *config.Config,
) gin.H {
	return gin.H{
		"User": gin.H{
			"Name":                      "admin",
			"ServerId":                  cfg.ServerId,
			"Id":                        userId,
			"HasPassword":               true,
			"HasConfiguredPassword":     true,
			"HasConfiguredEasyPassword": false,
			"EnableAutoLogin":           false,
			"LastLoginDate":             "2025-05-26T19:38:09.0167094Z",
			"LastActivityDate":          "2025-05-26T19:38:09.0167094Z",
			"Configuration": gin.H{
				"PlayDefaultAudioTrack":      true,
				"SubtitleLanguagePreference": "",
				"DisplayMissingEpisodes":     false,
				"GroupedFolders":             gin.H{},
				"SubtitleMode":               "Default",
				"DisplayCollectionsView":     false,
				"EnableLocalPassword":        false,
				"OrderedViews":               []interface{}{},
				"LatestItemsExcludes":        []interface{}{},
				"MyMediaExcludes":            []interface{}{},
				"HidePlayedInLatest":         true,
				"RememberAudioSelections":    true,
				"RememberSubtitleSelections": true,
				"EnableNextEpisodeAutoPlay":  true,
				"CastReceiverId":             "",
			},
			"Policy": gin.H{
				"IsAdministrator":                  true,
				"IsHidden":                         true,
				"EnableCollectionManagement":       false,
				"EnableSubtitleManagement":         false,
				"EnableLyricManagement":            false,
				"IsDisabled":                       false,
				"BlockedTags":                      []interface{}{},
				"AllowedTags":                      []interface{}{},
				"EnableUserPreferenceAccess":       true,
				"AccessSchedules":                  []interface{}{},
				"BlockUnratedItems":                []interface{}{},
				"EnableRemoteControlOfOtherUsers":  true,
				"EnableSharedDeviceControl":        true,
				"EnableRemoteAccess":               true,
				"EnableLiveTvManagement":           true,
				"EnableLiveTvAccess":               true,
				"EnableMediaPlayback":              true,
				"EnableAudioPlaybackTranscoding":   true,
				"EnableVideoPlaybackTranscoding":   true,
				"EnablePlaybackRemuxing":           true,
				"ForceRemoteSourceTranscoding":     false,
				"EnableContentDeletion":            true,
				"EnableContentDeletionFromFolders": []interface{}{},
				"EnableContentDownloading":         true,
				"EnableSyncTranscoding":            true,
				"EnableMediaConversion":            true,
				"EnabledDevices":                   []interface{}{},
				"EnableAllDevices":                 true,
				"EnabledChannels":                  []interface{}{},
				"EnableAllChannels":                true,
				"EnabledFolders":                   []interface{}{},
				"EnableAllFolders":                 true,
				"InvalidLoginAttemptCount":         0,
				"LoginAttemptsBeforeLockout":       -1,
				"MaxActiveSessions":                0,
				"EnablePublicSharing":              true,
				"BlockedMediaFolders":              []interface{}{},
				"BlockedChannels":                  []interface{}{},
				"RemoteClientBitrateLimit":         0,
				"AuthenticationProviderId":         "Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider",
				"PasswordResetProviderId":          "Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider",
				"SyncPlayAccess":                   "CreateAndJoinGroups",
			},
		},
		"SessionInfo": gin.H{
			"PlayState": gin.H{
				"CanSeek":       false,
				"IsPaused":      false,
				"IsMuted":       false,
				"RepeatMode":    "RepeatNone",
				"PlaybackOrder": "Default",
			},
			"AdditionalUsers": []interface{}{},
			"Capabilities": gin.H{
				"PlayableMediaTypes": []string{
					"Audio",
					"Video",
				},
				"SupportedCommands": []string{
					"MoveUp",
					"MoveDown",
					"MoveLeft",
					"MoveRight",
					"PageUp",
					"PageDown",
					"PreviousLetter",
					"NextLetter",
					"ToggleOsd",
					"ToggleContextMenu",
					"Select",
					"Back",
					"SendKey",
					"SendString",
					"GoHome",
					"GoToSettings",
					"VolumeUp",
					"VolumeDown",
					"Mute",
					"Unmute",
					"ToggleMute",
					"SetVolume",
					"SetAudioStreamIndex",
					"SetSubtitleStreamIndex",
					"DisplayContent",
					"GoToSearch",
					"DisplayMessage",
					"SetRepeatMode",
					"SetShuffleQueue",
					"ChannelUp",
					"ChannelDown",
					"PlayMediaSource",
					"PlayTrailers",
				},
				"SupportsMediaControl":         true,
				"SupportsPersistentIdentifier": false,
			},
			"RemoteEndPoint": "127.0.0.1",
			"PlayableMediaTypes": []string{
				"Audio",
				"Video",
			},
			"Id":       "14294dbbaf6efe83a74400782b56a5c6",
			"UserId":   userId,
			"UserName": "admin",
			"ServerId": cfg.ServerId,
			"SupportedCommands": []string{
				"MoveUp",
				"MoveDown",
				"MoveLeft",
				"MoveRight",
				"PageUp",
				"PageDown",
				"PreviousLetter",
				"NextLetter",
				"ToggleOsd",
				"ToggleContextMenu",
				"Select",
				"Back",
				"SendKey",
				"SendString",
				"GoHome",
				"GoToSettings",
				"VolumeUp",
				"VolumeDown",
				"Mute",
				"Unmute",
				"ToggleMute",
				"SetVolume",
				"SetAudioStreamIndex",
				"SetSubtitleStreamIndex",
				"DisplayContent",
				"GoToSearch",
				"DisplayMessage",
				"SetRepeatMode",
				"SetShuffleQueue",
				"ChannelUp",
				"ChannelDown",
				"PlayMediaSource",
				"PlayTrailers",
			},
		},
		"AccessToken": accessToken,
		"ServerId":    cfg.ServerId,
	}
}
